### ISSUE TITLE
this package not used !!!! what fuck ????

### ISSUE THREAD

**Issue by jin-pin-mei-le** [hsiafan/httpdump#47]

**Comment by jin-pin-mei-le** [comment]
Can't capture https

**Comment by cupen** [comment]
@jin-pin-mei-le What shit are you talking about?  This project is very useful, you should apologize to author.
https is not http, it's http & tls. So you want **https**dump right?  Here is it https://github.com/mitmproxy/mitmproxy

btw: 瞎骂些啥…… 你又不懂欣赏，还这么大口气。下次碰到问题虚心请教人家。
